### ISSUE TITLE
SS4 compatible version?

### ISSUE THREAD

**Issue by bummzack** [tractorcow/silverstripe-opengraph#21]
Is this module going to get updated for SilverStripe 4?

**Comment by bummzack** [comment]
Should I create a PR for this, or is it already in the works?

**Comment by tractorcow** [comment]
You can make a PR if you like. I'm not planning on upgrading this myself though, I'm afraid.

**Comment by Pinchcliffe** [comment]
@bummzack Are you currently updating this to SS4? Seems like the core Object class has been removed from the framework.

**Comment by bummzack** [comment]
@Pinchcliffe haven't had the time yet. But I'll probably tackle this some time soon because I think the module is really useful. Yeah, the core Object class has been removed and traits have been used to add commonly used functionality (such as "Injectable"). I don't think this is going to cause much of an issue… or did you already start an upgrade to ss4 and hit a wall?

**Comment by Pinchcliffe** [comment]
I've started to upgrade it to SS4, but I'm stuck hehe. Think I'll just wait for an updated version of this package :-)

**Comment by bummzack** [comment]
Push the changes to your fork then… so that somebody can pick up your work :)

**Comment by wernerkrauss** [comment]
For the sake of documentation: @Pinchcliffe 's work: See #22

**Comment by bummzack** [comment]
I'm closing this, since SS4 version is ready.
@tractorcow could you tag 4.0.1?

**Comment by tractorcow** [comment]
Ok done.
