### ISSUE TITLE
Yaml config 

### ISSUE THREAD

**Issue by teundirectlease** [tractorcow/silverstripe-opengraph#31]
I love the module.

I extended OpenGraphObjectExtension so that i have all my logic in one extension.

I wan't to add my own extension to the Page class but i can't override the yaml file since the replace function hasn't been added yet(https://github.com/silverstripe/silverstripe-config/issues/32):

Is it possible to remove the _config/Extensions.yaml ? The content could be replaced to mysite/_config/OpenGraph.yml so that it is configureable and adds more freedom. A simple delete and an update to the README should be enough ?

**Comment by tractorcow** [comment]
You could try using dependency injection to replace the `OpenGraphObjectExtension` class with a custom one?

**Comment by tractorcow** [comment]
@teundirectlease you can now use keyed extensions via YML to either:
 - replace the `opengraph` extension with a new extension, or,
 - set `opengraph` to null to disable that extension.

I hope that helps

```yaml


---
Name: disableog
After:
  - '#opengraphextensions'
---
Page:
  extensions:
    opengraph: null
```

**Comment by teundirectlease** [comment]
@tractorcow you are a legend! many thanks :-D
